language: node_js

before_install:
    - npm install -g grunt-cli

install:
    - npm install
    - grunt install

before_script:
    - grunt forever:app:start

script:
    - grunt test:unit

services:
    - redis-server
    - mongodb
